include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 85

analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_private_typedef_functions: ignore
    avoid_returning_this: ignore
    avoid_setters_without_getters: ignore
    cascade_invocations: ignore
    depend_on_referenced_packages: ignore
    directives_ordering: ignore
    document_ignores: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    no_adjacent_strings_in_list: ignore
    null_check_on_nullable_type_parameter: ignore
    only_throw_errors: ignore
    parameter_assignments: ignore
    prefer_constructors_over_static_methods: ignore
    prefer_int_literals: ignore
    require_trailing_commas: ignore
    unnecessary_await_in_return: ignore
    unnecessary_library_directive: ignore
    unnecessary_library_name: ignore
    use_setters_to_change_properties: ignore
  exclude:
    #- lib/**.g.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    library_prefixes: false
    no_runtimeType_toString: false
    one_member_abstracts: false
    prefer_single_quotes: false
    public_member_api_docs: false
    unnecessary_brace_in_string_interps: false
