name: streamline
description: "CQRS/Mediator Pattern library for a streamlined Flutter development"
version: 1.4.3
homepage: https://github.com/JCKodel/streamline

screenshots:
  - description: "Simplified architecture diagram"
    path: diagram.png

environment:
  sdk: ^3.7.0
  flutter: ">=3.7.0"

dependencies:
  dart_mappable: ^4.5.0
  flutter:
    sdk: flutter
  rxdart: '>=0.26.0 <=0.28.0'

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
