name: streamline
description: "CQRS/Mediator Pattern library for a streamlined Flutter development"
version: 1.0.1
homepage: https://github.com/JCKodel/streamline

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  dart_mappable: ^4.3.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
